"""Initial migration

Revision ID: 87beb015844f
Revises: 
Create Date: 2026-09-26 07:25:13.134712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87beb015844f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('inventory_manager', 'warehouse_staff', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('uom', sa.String(length=50), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='operationtype'), nullable=False),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'waiting', 'ready', 'done', 'canceled', name='operationstatus'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_operations_reference', 'operations', ['reference'], unique=False)
    op.create_index('ix_operations_status', 'operations', ['status'], unique=False)
    op.create_index('ix_operations_type', 'operations', ['type'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('per_unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_stock_product_location')
    )
    op.create_index(op.f('ix_stock_location_id'), 'stock', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_product_id'), 'stock', ['product_id'], unique=False)
    op.create_table('move_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='movedirection'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_move_history_date', 'move_history', ['date'], unique=False)
    op.create_index('ix_move_history_operation_id', 'move_history', ['operation_id'], unique=False)
    op.create_table('operation_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Double(), nullable=False),
    sa.Column('done_quantity', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_lines_operation_id'), 'operation_lines', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_lines_operation_id'), table_name='operation_lines')
    op.drop_table('operation_lines')
    op.drop_index('ix_move_history_operation_id', table_name='move_history')
    op.drop_index('ix_move_history_date', table_name='move_history')
    op.drop_table('move_history')
    op.drop_index(op.f('ix_stock_product_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_location_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index('ix_operations_type', table_name='operations')
    op.drop_index('ix_operations_status', table_name='operations')
    op.drop_index('ix_operations_reference', table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('locations')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
